{
  "name": "TryCatchDemo",
  "description": "TryCatch activity catches a specified exception type in a sequence or activity, and either displays an error notification or dismisses it and continues the execution. As a mechanism, TryCatch runs the activities in the Try block and, if an error takes place, executes the activities in the Catches block. The Finally block is only executed when no exceptions are thrown or when an exception is caught and handled in the Catches block (without being re-thrown). ",
  "main": "Main.xaml",
  "dependencies": {
    "UiPath.Excel.Activities": "[2.9.5]",
    "UiPath.System.Activities": "[20.10.4]",
    "UiPath.UIAutomation.Activities": "[20.10.9]"
  },
  "webServices": [],
  "entitiesStores": [],
  "schemaVersion": "4.0",
  "studioVersion": "20.10.6.0",
  "projectVersion": "1.0.0.0",
  "runtimeOptions": {
    "autoDispose": false,
    "isPausable": true,
    "requiresUserInteraction": true,
    "supportsPersistence": false,
    "excludedLoggedData": [
      "Private:*",
      "*password*"
    ],
    "executionType": "Workflow",
    "readyForPiP": false,
    "startsInPiP": false
  },
  "designOptions": {
    "projectProfile": "Developement",
    "outputType": "Process",
    "libraryOptions": {
      "includeOriginalXaml": false,
      "privateWorkflows": []
    },
    "processOptions": {
      "ignoredFiles": []
    },
    "fileInfoCollection": [],
    "modernBehavior": false
  },
  "expressionLanguage": "VisualBasic",
  "entryPoints": [
    {
      "filePath": "Main.xaml",
      "uniqueId": "362e4d75-d011-4c6d-b269-a962e201e759",
      "input": [],
      "output": []
    }
  ],
  "isTemplate": false,
  "templateProjectData": {},
  "publishData": {}
}